Algoritmo "Triangulo com asterisco"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/12/2024
Var
   n: real


Inicio
escreval("Digite um  valor: ")
leia(n)
se n = 5 entao
escreval("TRIÂNGULO")
escreval("*")
escreval("**")
escreval("***")
escreval("****")
escreval("*****")
senao
escreval("NÚMERO INVÁLIDO: ")
  fimse
Fimalgoritmo